AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for testing AWS Gradle plugin
Resources:
  EncryptedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'demo-bucket-${AWS::Region}-${AWS::AccountId}'
    DeletionPolicy: Delete